In [9]:
import pandas as pd # Python library used for working with data sets
A = pd.read_csv("pythonmatrixA.csv") #Read the CSV into a DataFrame
A=A.to_numpy() #formatting the Array
print("A:")
print(A)
import pandas as pd
B = pd.read_csv("pythonvectorB.csv")#Read the vector from csv
B=B.to_numpy()
print("B:")
print(B)

A:
[[4 2 4 6]
 [5 3 6 9]
 [6 4 8 1]]
B:
[[6]
 [7]
 [8]]


In [10]:
import numpy as np
#library for linear algebra
import scipy.linalg as lg 
#Defining a square matrix 
A = np.array([[2,4,6,8],[3,6,9,12],[4,8,12,16],[5,10,15,20]])
print("A:")
print(A)
#LU-decomposition 
#A = PLU
P,L,U = lg.lu(A)#fuction lu for matrix A =>lu(A)
#l= Lower Tringular Matrix
#U= Uppr Tringular Matrix
#P = Unit Vector
print("L")
print(L)
print("U")
print(U)

A:
[[ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]
 [ 5 10 15 20]]
L
[[1.   0.   0.   0.  ]
 [0.6  1.   0.   0.  ]
 [0.8  0.5  1.   0.  ]
 [0.4  0.25 0.   1.  ]]
U
[[ 5.00000000e+00  1.00000000e+01  1.50000000e+01  2.00000000e+01]
 [ 0.00000000e+00 -8.88178420e-16 -1.33226763e-15 -1.77635684e-15]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]


In [40]:
# Diagonalization of matrix
  
import numpy as np
A=np.array([[3,-3,9],[-3,11,3],[9,3,3]])
eigenvalues,eigenvectors = np.linalg.eig(A)
P= eigenvectors

B=A.transpose() # Transpose of given array

if np.array_equal(A,B):#compare arrays using array_equal() method
    print("matrix is symmetric")
D = np.zeros((3,3))
for i in range(3):
    D[i,i]= eigenvalues[i]
P_inv= np.linalg.inv(P)
print('P:')
print(P) # eigensvectors matrix 
print('D:')
print(D)
print('P_inv:') # inverse of eigensvector matrix
print(P_inv)
print('eigenvalues:') 
d =P*A*P_inv
print(d)
print(eigenvalues)# for eigensvalues pairs 
        

    
    

matrix is symmetric
P:
[[ 0.72547625 -0.6882472   0.14018702]
 [-0.21764288 -0.22941573  0.88874698]
 [ 0.65292863  0.6882472   0.43643602]]
D:
[[12.  0.  0.]
 [ 0. -7.  0.]
 [ 0.  0. 12.]]
P_inv:
[[ 7.25476250e-01 -4.04482640e-01  5.90648703e-01]
 [-6.88247202e-01 -2.29415734e-01  6.88247202e-01]
 [-8.94568655e-18  9.66906975e-01  3.22302325e-01]]
eigenvalues:
[[ 1.57894737e+00 -8.35152135e-01  7.45211560e-01]
 [-4.49376299e-01  5.78947368e-01  1.83503287e+00]
 [-5.25680534e-17  1.99641306e+00  4.21993031e-01]]
[12. -7. 12.]


In [4]:
#EIGEN PAIRS 
import numpy as np
A=np.array([[3,-3,9],[-3,11,3],[9,3,3]])
eigenvalues,eigenvectors = np.linalg.eig(A)
print('eigens-pair ',eigenvalues,"\n", eigenvectors)

eigens-pair  [12. -7. 12.] 
 [[ 0.72547625 -0.6882472   0.14018702]
 [-0.21764288 -0.22941573  0.88874698]
 [ 0.65292863  0.6882472   0.43643602]]


In [3]:
#solve the equation Ax=b
import numpy as np
import scipy.linalg as lg
A = np.array([[22,33,44],[55,66,77],[11,22,88]])
B = np.array([[12],[14],[15]])
#AX=B
#LUX =B
#LV=B ...(Ux=V)
#
LU,V=lg.lu_factor(A)#
X= lg.lu_solve((LU,V),B)
print("X")
print(X)

#solution
import pandas as pandas
import numpy as numpy
from scipy.linalg import solve
from numpy.linalg import matrix_rank


numberOfRows_MatrixA, numberOfColumns_MatrixA = A.shape

numberOfRows_VectorB, numberOfColumns_VectorB = B.shape
print("Matrix A\t\t\tVector B")
for i in range(numberOfRows_MatrixA):
    for j in range(numberOfColumns_MatrixA):
        space = ' '
        if(A[i][j] < 0):
            space = ''
        print(space + format(numpy.round(A[i][j], 2)), end = "\t")
    print(" ", end = "\t")
    for j in range(numberOfColumns_VectorB):
        space = ' '
        if(B[i][j] < 0):
            space = ''
        print(space + format(numpy.round(B[i][j], 2)), end = "\t")
    print(" ")
print(" ")
print("Vector X")
vectorX = solve(A, B)
for i in range(numberOfColumns_MatrixA):
    for j in range(numberOfColumns_VectorB):
        space = ' '
        if(vectorX[i][j] < 0):
            space = ''
        print(space + format(numpy.round(vectorX[i][j], 2)))
print(" ")
rankOfMatrixA = matrix_rank(A);
augmentedMatrix = numpy.hstack((A, B))
rankOfAugmentedMatrix = matrix_rank(augmentedMatrix)
if(rankOfMatrixA == rankOfAugmentedMatrix):
    if(rankOfMatrixA == numberOfColumns_MatrixA):
        print("The system has a unique solution.")
    else:
        print("The system has infinite-many solutions.")
else:
    print("The system is inconsistent.")


X
[[-0.84242424]
 [ 0.83636364]
 [ 0.06666667]]
Matrix A			Vector B
 22	 33	 44	 	 12	 
 55	 66	 77	 	 14	 
 11	 22	 88	 	 15	 
 
Vector X
-0.84
 0.84
 0.07
 
The system has a unique solution.


In [35]:
#sine function
#numpy.sin(input) where input can be a single number as well as a NumPy Array and 
#The Numpy sin function takes an angle in radians as an argument.
import numpy as np

A = np.array([[0, 30,45],[90,30,20],[30,60,90]])
print("inputs")
print(A)
z = np.sin(A)
print("i/p was taken as Radians:\n",z)
B = np.sin(A*np.pi/180)
print("i/p was taken as Degree:")
print(B)


inputs
[[ 0 30 45]
 [90 30 20]
 [30 60 90]]
i/p was taken as Radians:
 [[ 0.         -0.98803162  0.85090352]
 [ 0.89399666 -0.98803162  0.91294525]
 [-0.98803162 -0.30481062  0.89399666]]
i/p was taken as Degree:
[[0.         0.5        0.70710678]
 [1.         0.5        0.34202014]
 [0.5        0.8660254  1.        ]]


In [39]:
#Exponential Values of 2-D NumPy Array
#np.exp(arr)
import numpy as np
A= np.array([[20,20,30],[40,60,90],[20,40,78]])
B=np.exp(A)
print("Exponential of matrix:\n",B)


Exponential of matrix:
 [[4.85165195e+08 4.85165195e+08 1.06864746e+13]
 [2.35385267e+17 1.14200739e+26 1.22040329e+39]
 [4.85165195e+08 2.35385267e+17 7.49841700e+33]]


In [51]:
# sigmoid function = 1/(1 + np.exp(-x))
import numpy as np
A= np.array([[0,0.2,0.3],[0.9,0.6,0.8],[30,0.5,0.1]])
B= 1/(1 + np.exp(-A))
print("values of sigmoid function:\n",B)
#using def sigmoid(x):
#    return 1.0 / (1.0 + np.exp(-x))
def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))
print("\n2nd methord: \n", sigmoid(A))

values of sigmoid function:
 [[0.5        0.549834   0.57444252]
 [0.7109495  0.64565631 0.68997448]
 [1.         0.62245933 0.52497919]]

2nd methord: 
 [[0.5        0.549834   0.57444252]
 [0.7109495  0.64565631 0.68997448]
 [1.         0.62245933 0.52497919]]
